---
{{- range $namespace := .Values.workspace.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $namespace }}-reloader-role
  namespace: {{ $namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - list
  - get
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - deployments
  - statefulsets
  verbs:
  - list
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
{{- end }}

---
{{- range $namespace := .Values.workspace.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: {{ $namespace }}-reloader-role-binding
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $namespace }}-reloader-role
---
{{- end }}
