{{- range $namespace := .Values.workspace.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: {{ $namespace }}-rolebinding
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $namespace }}-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $namespace }}-role
---
{{- end }}


{{- range $namespace := .Values.workspace.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: {{ $namespace }}-agent-rolebinding
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $namespace }}-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: e6data-agent
---
{{- end }}

{{- $dot := . }}
{{- range $namespace := .Values.workspace.namespaces }}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: {{ $namespace }}-e6data-rolebinding
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "e6data.serviceAccountName.server" $dot }}
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $namespace }}-role
---
{{- end }}



