apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "e6data.name" . }}-e6data-ops-role
  {{ include "e6data.namespace" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
      - ingresses
      - configmaps
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
      - patch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - update  
      - delete 
  - apiGroups:
      - "batch"
    resources:
      - jobs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - daemonsets/status
      - deployments/status
      - statefulsets/status
    verbs:
      - get
      - list
      - watch 
      - create
      - update
      - delete  
      - patch    

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: {{ include "e6data.name" . }}-e6data-ops-role-binding
  {{ include "e6data.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: e6data-operator
    namespace: {{ .Values.operator.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "e6data.name" . }}-e6data-ops-role
