{{- range $namespace := .Values.workspace.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $namespace }}-ops-role
  namespace: {{ $namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
      - ingresses
      - configmaps
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
      - patch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - update  
      - delete 
  - apiGroups:
      - "batch"
    resources:
      - jobs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - daemonsets/status
      - deployments/status
      - statefulsets/status
    verbs:
      - get
      - list
      - watch 
      - create
      - update
      - delete  
      - patch    
{{- end }}

---
{{- $dot := . }}
{{- range $namespace := .Values.workspace.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: {{ $namespace }}-ops-role-binding
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: e6data-operator
  {{ include "e6data.namespace" $dot | indent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $namespace }}-ops-role
---
{{- end }}
