{{- if .Values.serviceAccounts.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "e6data.server.labels" . | nindent 4 }}
  name: e6data-operator
{{ include "e6data.namespace" . | indent 2 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpSaEmail.operator }}
{{- end }}
    
