name: Update Helm Packages

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "hemant-uniphi"
          git config --global user.email "hemant@e6x.io"

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Run commands
        run: |
          PR_NUMBER=$(git log --format=%B -n 1 | grep -oE '#[0-9]+' | awk -F'#' '{print $2}')
          PR_TITLE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" | jq -r '.title')
          PR_BRANCH=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" | jq -r '.head.ref')

          cd "$(git rev-parse --show-toplevel)"
          cd charts/workspace
          CURRENT_VERSION=$(find . -name "workspace-*.tgz" | sed -E 's/.*workspace-(.*).tgz/\1/')
          VERSION_NUMBER_ARRAY=(${CURRENT_VERSION//./ })
          MAJOR=${VERSION_NUMBER_ARRAY[0]}
          MINOR=${VERSION_NUMBER_ARRAY[1]}
          PATCH=${VERSION_NUMBER_ARRAY[2]}

          if [[ "$PR_TITLE" == *"[Major]"* ]]; then
            MAJOR=$((MAJOR + 1))
          elif [[ "$PR_TITLE" == *"[Minor]"* ]]; then
            MINOR=$((MINOR + 1))
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          helm package .
          rm -rf "workspace-${CURRENT_VERSION}.tgz"
          mv e6data-operator-0.1.0.tgz "workspace-${NEW_VERSION}.tgz"
          sed -i "s/version: .*/version: ${NEW_VERSION}/" Chart.yaml

          cd "$(git rev-parse --show-toplevel)"
          cd charts/operator
          CURRENT_VERSION=$(find . -name "operator-*.tgz" | sed -E 's/.*operator-(.*).tgz/\1/')
          VERSION_NUMBER_ARRAY=(${CURRENT_VERSION//./ })
          MAJOR=${VERSION_NUMBER_ARRAY[0]}
          MINOR=${VERSION_NUMBER_ARRAY[1]}
          PATCH=${VERSION_NUMBER_ARRAY[2]}

          if [[ "$PR_TITLE" == *"[Major]"* ]]; then
            MAJOR=$((MAJOR + 1))
          elif [[ "$PR_TITLE" == *"[Minor]"* ]]; then
            MINOR=$((MINOR + 1))
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          helm package .
          rm -rf "operator-${CURRENT_VERSION}.tgz"
          mv e6data-operator-0.1.0.tgz "operator-${NEW_VERSION}.tgz"
          sed -i "s/version: .*/version: ${NEW_VERSION}/" Chart.yaml

          cd "$(git rev-parse --show-toplevel)"
          git add .
          git commit -m "Updating packages for Helm"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true